name: Latest douban activities workflow
on:
  schedule:
    # Runs every 2 hour
    - cron: "0 */2 * * *"

jobs:
  update-readme-with-douban-activities:
    name: Update this repo's README with douban activities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README.md with douban user's activities
        uses: itgoyo/douban-activity-readme@v1
        with:
          uid: 62943420
          max_count: 10
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
